# Generated by Django 5.0.6 on 2024-06-13 04:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticator', '0002_alter_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('loan_type', models.CharField(max_length=10)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(12)])),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticator.person')),
            ],
        ),
    ]
