# Generated by Django 5.0.6 on 2024-06-13 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(150000)]),
        ),
    ]
