# Generated by Django 5.0.6 on 2024-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Welcome', '0002_alter_loan_loan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField()),
            ],
        ),
    ]
