# Generated by Django 5.0.6 on 2024-06-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(auto_created=True, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('annual_income', models.IntegerField()),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticator.person')),
            ],
        ),
    ]
